### ISSUE TITLE
Removal Request, CS Homework Solution

### ISSUE THREAD

**Issue by jsanders89** [bmn28/cs61b#1]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. A post in this repository contains a solution to the Guitar Hero homework assignment that is identical to the one we use in our classes.

https://github.com/bmn28/cs61b/blob/master/hw4/synthesizer/GuitarString.java

This post is indexed by Github's search, enabling current students to easily find it and submit it as their own work.

Would you be willing to remove this post or make it private in order to help us enforce our academic policy?

By removing the post, you would be removing tools that our students could use in academic misconduct.

Thank you, Jonathan Sanders CSE 14X Program Coordinator University of Washington jsanders@cs.washington.edu

**Comment by bmn28** [comment]
Yes, I will remove the code.
